name: Create Development PR

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request into develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: merge ${{ github.ref_name }} into develop"
          branch: develop
          base: develop
          head: ${{ github.ref_name }}
          title: "Feature: ${{ github.ref_name }}"
          body: |
            Este pull request foi criado automaticamente para integrar as alterações da branch **${{ github.ref_name }}** na branch develop.
          draft: false
          labels: feature
